# Generated by Django 2.0.2 on 2020-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200604_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='being_delivared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refaund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refaund_request',
            field=models.BooleanField(default=False),
        ),
    ]
