# Generated by Django 2.0.2 on 2020-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200609_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
